trigger:
- part2

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  image: "rphredacr.azurecr.io/pytest:v1"
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build the image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

- stage: Test
  displayName: Test app
  dependsOn: Build
  jobs:
  - job: Test
    displayName: Test
    steps:
    - script: |
        docker pull $(image)
        docker run --rm $(image) pytest
      displayName: Test the app
