trigger:
- part2

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  image: "rphredacr.azurecr.io/pytest:v1"
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build the image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

- stage: Test
  displayName: Test image
  dependsOn: Build

  jobs:
  - job: Test
    displayName: Test
    steps:

    - task: AzureCLI@2
      displayName: Login to ACR
      inputs:
        azureSubscription: subscription-1-service-connection
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name rphredacr

    - script: |
        docker pull $(image)
        docker run --rm $(image) pytest
      displayName: Run tests
